/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/silla.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.polySurface1.geometry} material={materials.Fabric} scale={0.11} />
      <mesh geometry={nodes.polySurface2.geometry} material={materials.Fabric} scale={0.11} />
      <mesh geometry={nodes.polySurface13.geometry} material={materials.Wood} scale={0.11} />
    </group>
  )
}

useGLTF.preload('/silla.glb')
